base_url = "https://tsai002.github.io/"
title = "Ciao!"
minify_html = true
generate_feeds = true
feed_limit = 20
generate_sitemap = true

[markdown]
bottom_footnotes = true

[markdown.highlighting]
light_theme = "github-light"
dark_theme = "github-dark"
